version: "3.8"

services:
  api:
    build: .
    ports:
      - "${PORT:-8000}:${PORT:-8000}" 
    environment:
      - PORT=${PORT:-8000}
      - UVICORN_RELOAD=true  # Permite recarga automática en desarrollo
    volumes:
      - .:/app  # Mapea el código local dentro del contenedor
    command: ["sh", "-c", "fastapi dev src/main.py --host 0.0.0.0 --port ${PORT} --reload"]